### ISSUE TITLE
This plug-in does not work with the new gatsby-image-plugin or Gatsby version 3

### ISSUE THREAD

**Issue by wildpow** [datocms/gatsby-remark-images-datocms#5]
The Error `TypeError: Cannot read property 'forceBlurhash' of null` happens when trying to upgrade Gatsby from v2 to v3 and use the new `gatsby-image-plugin`.

Here is the stack trace error I get in GraphiQL
```
{
  "errors": [
    {
      "message": "Cannot read property 'forceBlurhash' of null",
      "locations": [
        {
          "line": 8,
          "column": 9
        }
      ],
      "path": [
        "datoCmsNewBlog",
        "contentNode",
        "childMarkdownRemark",
        "html"
      ],
      "stack": [
        "TypeError: Cannot read property 'forceBlurhash' of null",
        "    at _callee$ (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:76:34)",
        "    at tryCatch (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:63:40)",
        "    at Generator.invoke [as _invoke] (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:293:22)",
        "    at Generator.next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:118:21)",
        "    at asyncGeneratorStep (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:15:103)",
        "    at _next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:17:194)",
        "    at /Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:17:364",
        "    at new Promise (<anonymous>)",
        "    at /Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:17:97",
        "    at /Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-source-datocms/hooks/sourceNodes/createTypes/utils/getBase64.js:130:18",
        "    at _callee$ (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-remark-images-datocms/utils/replace.js:72:20)",
        "    at tryCatch (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:63:40)",
        "    at Generator.invoke [as _invoke] (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:293:22)",
        "    at Generator.next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/regenerator-runtime/runtime.js:118:21)",
        "    at asyncGeneratorStep (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-remark-images-datocms/utils/replace.js:3:103)",
        "    at _next (/Users/wildpow/Documents/GitHub/esc-gatsby3-tailwind/node_modules/gatsby-remark-images-datocms/utils/replace.js:5:194)"
      ]
    }
  ],
  
```

**Comment by wildpow** [comment]
[Structured text](https://www.datocms.com/docs/content-modelling/structured-text) makes this markdown issue mute. At least for someone with the ability to refactor all their blog posts 🎉

**Comment by stefanoverna** [comment]
We'll take a look at this @wildpow!

**Comment by stefanoverna** [comment]
Alright, v0.1.1 should fix the issue! Thanks for reporting @wildpow!
